[project]
name = "study-assistant"
version = "0.1.0"
description = "RAG based personalized study assistant"
requires-python = ">=3.12"
dependencies = [
    "chromadb",
    "google-genai",
    "groq>=0.37.1",
    "langchain",
    "langchain-chroma",
    "langchain-community",
    "langchain-core",
    "langchain-groq>=1.1.3",
    "pdf2image",
    "pillow",
    "pydantic",
    "pymupdf4llm",
    "python-dotenv",
    "streamlit",
]
